name: "Remote HA"
description: "Remote access to local Home Assistant OS by tunnel"
version: "1.0.1"
slug: "remote_ha"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  remoteID: "Please get at Tinymation.com" 
schema:
  remoteID: str  
