[common]
server_port = 7000
server_addr = server.tinymation.com
log_file = /share/frpc.log
log_level = info
log_max_days = 3
[http_020007a29b47]
type = http
local_ip = 127.0.0.1
local_port = 8123
subdomain = 001c1
meta_auth_valid_to = 1924905600000
meta_auth_key = de101b22-df7f-4671-9fe4-c052a22042e6
use_gzip = true
